package uga.cs.capitalquizapp;

import android.content.ContentValues;
import android.content.Context;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteOpenHelper;
import android.util.Log;

import java.util.ArrayList;
import java.util.List;
import java.util.Set;

public class QuestionsData {
    public static final String DEBUG_TAG = "JobLeadsData";

    private SQLiteDatabase db;
    private SQLiteOpenHelper questionsSqlOpenHelper;
    private static final String[] allColumns = {
            QuestionsSqlOpenHelper.QUESTIONS_COLUMN_ID,
            QuestionsSqlOpenHelper.QUESTIONS_COLUMN_STATE,
            QuestionsSqlOpenHelper.QUESTIONS_CAPITAL,
            QuestionsSqlOpenHelper.QUESTIONS_COLUMN_CITY1,
            QuestionsSqlOpenHelper.QUESTIONS_COLUMN_CITY2
    };

    public QuestionsData( Context context ) {
        this.questionsSqlOpenHelper = QuestionsSqlOpenHelper.getInstance( context );
    }

    // Open the database
    public void open() {
        db = questionsSqlOpenHelper.getWritableDatabase();

        Log.d( DEBUG_TAG, "JobLeadsData: db open" );
    }

    // Close the database
    public void close() {
        if( questionsSqlOpenHelper != null ) {
            questionsSqlOpenHelper.close();
            //SQLiteDatabase.deleteDatabase("capital");
            Log.d(DEBUG_TAG, "JobLeadsData: db closed");
        }
    }

    // Retrieve all job leads as a List.
    // This is how we restore persistent objects stored as rows in the job leads table in the database.
    // For each retrieved row, we create a new JobLead (Java object) instance and add it to the list.

    public List<Question> retrieveAllJobLeads(Set<Integer> ids) {
        ArrayList<Question> questions = new ArrayList<>();
        Cursor cursor = null;
        try {


            StringBuilder s = new StringBuilder();
            s.append(QuestionsSqlOpenHelper.QUESTIONS_COLUMN_ID + " in ");
            s.append("(");

            for (int id : ids) {
                s.append(id);
                s.append(",");
            }
            s.deleteCharAt(s.length() - 1);

            s.append(")");

            // Execute the select query and get the Cursor to iterate over the retrieved rows

            cursor = db.query( QuestionsSqlOpenHelper.TABLE_QUESTIONS, allColumns,
                    s.toString(), null, null, null, null );
            // collect all job leads into a List
            if( cursor.getCount() > 0 ) {
                while( cursor.moveToNext() ) {
                    long id = cursor.getLong( cursor.getColumnIndex( QuestionsSqlOpenHelper.QUESTIONS_COLUMN_ID ) );
                    String state = cursor.getString( cursor.getColumnIndex( QuestionsSqlOpenHelper.QUESTIONS_COLUMN_STATE ) );
                    String capital = cursor.getString( cursor.getColumnIndex( QuestionsSqlOpenHelper.QUESTIONS_CAPITAL ) );


                    String city1 = cursor.getString( cursor.getColumnIndex( QuestionsSqlOpenHelper.QUESTIONS_COLUMN_CITY1 ) );









                    String city2 = cursor.getString( cursor.getColumnIndex( QuestionsSqlOpenHelper.QUESTIONS_COLUMN_CITY2 ) );
                    Question question = new Question(state , capital, city1, city2 );
                    question.setId( id );



                    questions.add(question);


                    Log.d( DEBUG_TAG, "Retrieved JobLead: " + question );
                }
            }
            Log.d( DEBUG_TAG, "Number of records from DB: " + cursor.getCount() );
        }
        catch( Exception e ){
            Log.d( DEBUG_TAG, "Exception caught: " + e );
        }
        finally{
            // we should close the cursor
            if (cursor != null) {
                cursor.close();
            }
        }
        return questions;
    }

    /*
    // Store a new job lead in the database
    public Question storeJobLead( Question question ) {

        // Prepare the values for all of the necessary columns in the table
        // and set their values to the variables of the JobLead argument.
        // This is how we are providing persistence to a JobLead (Java object) instance
        // by storing it as a new row in the database table representing job leads.
        ContentValues values = new ContentValues();
        values.put( QuestionsSqlOpenHelper.QUESTIONS_COLUMN_NAME, jobLead.getCompanyName());
        values.put( QuestionsSqlOpenHelper.QUESTIONS_COLUMN_PHONE, jobLead.getPhone() );
        values.put( QuestionsSqlOpenHelper.QUESTIONS_COLUMN_URL, jobLead.getUrl() );
        values.put( QuestionsSqlOpenHelper.QUESTIONS_COLUMN_COMMENTS, jobLead.getComments() );

        // Insert the new row into the database table;  the id (primary key) will be
        // automatically generated by the database system
        long id = db.insert( QuestionsSqlOpenHelper.TABLE_QUESTIONS, null, values );

        // store the id in the JobLead instance, as it is now persistent
        jobLead.setId( id );

        Log.d( DEBUG_TAG, "Stored new job lead with id: " + String.valueOf( jobLead.getId() ) );

        return jobLead;
    }




*/
}
